<script lang="ts">
  import "../app.css";
  import { page } from "$app/stores";
  import NotificationBell from "$lib/components/NotificationBell.svelte";
  import { loadEnv } from "$lib/env.svelte";
  import { authState, applyToken } from "$lib/auth.svelte";

  /** Token pasted into the unlock form. */
  let tokenInput = $state("");

  let { children } = $props();

  // Host facts (home dir, path separator) come from the daemon and are needed
  // by every panel that renders a filesystem path. Fetched once here so no
  // individual component has to.
  loadEnv();

  const navItems = [
    { href: "/", label: "Overview", id: "overview",
      icon: '<svg width="18" height="18" viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M2 8L8 2.5L14 8"/><path d="M4 7V13.5H12V7"/></svg>' },
    { href: "/memory", label: "Memory", id: "memory",
      icon: '<svg width="18" height="18" viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><ellipse cx="8" cy="4" rx="5" ry="2"/><path d="M3 4V12C3 13.1 5.2 14 8 14S13 13.1 13 12V4"/><path d="M3 8C3 9.1 5.2 10 8 10S13 9.1 13 8"/></svg>' },
    { href: "/logs", label: "Logs", id: "logs",
      icon: '<svg width="18" height="18" viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"><path d="M3 4H13M3 8H10M3 12H7"/></svg>' },
    { href: "/telemetry", label: "Telemetry", id: "telemetry",
      icon: '<svg width="18" height="18" viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round"><path d="M2.5 13V9.5M6 13V5.5M9.5 13V8M13 13V3"/></svg>' },
    { href: "/settings", label: "Settings", id: "settings",
      icon: '<svg width="18" height="18" viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"><circle cx="8" cy="8" r="2.5"/><path d="M8 1.5V3.5M8 12.5V14.5M1.5 8H3.5M12.5 8H14.5M3.3 3.3L4.7 4.7M11.3 11.3L12.7 12.7M12.7 3.3L11.3 4.7M4.7 11.3L3.3 12.7"/></svg>' },
    { href: "/help", label: "Help", id: "help",
      icon: '<svg width="18" height="18" viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><circle cx="8" cy="8" r="6.5"/><path d="M6 6.5C6 5.4 6.9 4.5 8 4.5S10 5.4 10 6.5C10 7.6 8 8.5 8 9.5"/><circle cx="8" cy="11.5" r="0.5" fill="currentColor" stroke="none"/></svg>' },
  ];

  /** Derive active nav item from current pathname */
  function isActive(href: string): boolean {
    const pathname = $page.url.pathname;
    if (href === "/") return pathname === "/";
    return pathname.startsWith(href);
  }
</script>

<svelte:head>
  <title>operad dashboard</title>
</svelte:head>

<header class="sticky top-0 z-50 border-b border-[var(--border)] bg-[var(--bg-primary)]">
  <div class="max-w-5xl mx-auto px-4 py-2 flex items-center justify-between">
    <div class="flex items-center gap-2">
      <span class="text-[var(--accent-blue)] font-bold text-sm">operad</span>
      <span class="text-[var(--text-muted)] text-xs">dashboard</span>
    </div>
    <div class="flex items-center gap-2">
      <nav class="flex gap-1">
        {#each navItems as item (item.id)}
          <a href={item.href} class:active={isActive(item.href)} title={item.label} aria-label={item.label}>
            {@html item.icon}
          </a>
        {/each}
      </nav>
      <NotificationBell />
    </div>
  </div>
</header>
<main class="max-w-5xl mx-auto main-content">
  {#if authState.unauthenticated}
    <!--
      The API is token-gated but static assets are not, so a browser that has
      not completed the handshake loads this page and then 401s on every
      request. Without this the user saw a wall of "HTTP 401" with no hint
      that a token exists.
    -->
    <section class="auth-gate">
      <h1>Authentication required</h1>
      <p>
        The dashboard API can start and stop processes, run scripts and install
        skills, so it needs the access token generated by your daemon.
      </p>
      <p>Run this on the machine hosting operad:</p>
      <pre><code>operad token</code></pre>
      <p>
        Open the <code>?token=…</code> URL it prints — that exchanges the token
        for a cookie and you will not need it again on this browser. Or paste
        the token here:
      </p>
      <form
        class="auth-form"
        onsubmit={(e) => { e.preventDefault(); applyToken(tokenInput); }}
      >
        <input
          type="password"
          bind:value={tokenInput}
          placeholder="dashboard token"
          autocomplete="off"
          spellcheck="false"
        />
        <button type="submit" disabled={tokenInput.trim() === ""}>Unlock</button>
      </form>
      <p class="auth-hint">
        The token lives in <code>&lt;state_dir&gt;/dashboard-token</code>. If the
        daemon is not running, start it with <code>operad boot</code>.
      </p>
    </section>
  {:else}
    {@render children()}
  {/if}
</main>

<style>
  .main-content { padding: 1rem; }
  @media (max-width: 768px) {
    .main-content { padding: 0.5rem; }
  }

  /* -- Authentication gate -- */
  .auth-gate {
    max-width: 34rem;
    margin: 4rem auto;
    padding: 1.75rem;
    border: 1px solid var(--border, #2a3140);
    border-radius: 0.75rem;
    background: var(--surface, #12161f);
    line-height: 1.6;
  }
  .auth-gate h1 {
    margin: 0 0 0.75rem;
    font-size: 1.15rem;
    font-weight: 600;
  }
  .auth-gate p { margin: 0 0 0.75rem; font-size: 0.9rem; }
  .auth-gate pre {
    margin: 0 0 0.75rem;
    padding: 0.6rem 0.8rem;
    border-radius: 0.4rem;
    background: var(--bg, #0b0e14);
    overflow-x: auto;
  }
  .auth-gate code { font-size: 0.85rem; }
  .auth-form { display: flex; gap: 0.5rem; margin-bottom: 0.75rem; }
  .auth-form input {
    flex: 1 1 auto;
    min-width: 0;
    padding: 0.5rem 0.65rem;
    border-radius: 0.4rem;
    border: 1px solid var(--border, #2a3140);
    background: var(--bg, #0b0e14);
    color: inherit;
    font-family: inherit;
  }
  .auth-form button {
    padding: 0.5rem 0.9rem;
    border-radius: 0.4rem;
    border: 1px solid var(--border, #2a3140);
    background: var(--surface-2, #1a2030);
    color: inherit;
    cursor: pointer;
  }
  .auth-form button:disabled { opacity: 0.5; cursor: default; }
  .auth-hint { font-size: 0.8rem; opacity: 0.75; }
</style>
